name: BUTLEREN.NO
favicon: null
layout_spectrum: 0.49639
typography_spectrum: 0.33727
title: matching QUALITY - choose SERVICE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64719430-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121212'
    - '#585a41'
    - '#938a88'
    - '#c0b8b5'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.08280503377318382
purpose: []
