name: BUTLEREN.NO
favicon: null
layout_spectrum: 0.49639
typography_spectrum: 0.33727
title: matchingQUALITY - chooseSERVICE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2f3e55'
    - '#effdfe'
    - '#5f7390'
    - '#c49677'
  brandStrength: 0.8220215043984354
  lightness: 0.8431502711027861
  saturation: 0.9199920389801264
  rhythmicContrast: 0.08280503377318382
purpose: []
